### PR TITLE
Allow infix notation on `invokes`, `returns` and `throws`

### PR DESCRIPTION
**Pull request by alexandrefavre4**
cf. https://github.com/mockative/mockative/pull/90

### CODE REVIEW

**Comment by alexandrefavre4** [comment]
@Nillerr Could you please have a look to the changes when you get a chance? I'd appreciate your feedback and, hopefully, merging it if everything looks good to you.

**Comment by alexandrefavre4** [comment]
@Nillerr @kris098e This pull request has been open for over 4 months. Can we merge it?

**Comment by Nillerr** [comment]
Hey @alexandrefavre4

Truth be told I lost a lot of motivation for working on Mockative with the realization that a fundamental change in Kotlin 2 broke Mockative, which is the reason why you haven't seen any activity from me in a long time. Thankfully @kris098e has taken over a lot of communication for this project.

Since I don't currently have a specific vision for Mockative, and don't foresee getting one while the future of the project remains uncertain, moving towards a MockK-like API may not be a bad thing since many Kotlin developers will know that already, so let's just get this PR merged.

**Review by Nillerr — APPROVED** [review]

**Comment by alexandrefavre4** [comment]
@Nillerr I completely understand your loss of motivation and I hope that future releases of Kotlin/KSP will unblock the situation for Mockative. I think that these changes still make sense even if you don't want to bring Mockative's API closer to MockK's, as infix notation will surely be appreciated by some developers and, importantly, remains optional.

**Pull request merged**
